### ISSUE TITLE
Cannot Find Jekyll

### ISSUE THREAD

**Issue by mzagaja** [dieghernan/algolia-jekyll-action#3]
See https://github.com/mzagaja/mzagaja.github.io/actions/runs/3523413057/jobs/5907545090#step:3:162 for the failure log. It seems like yesterday it stopped being able to find the jekyll command.

```
bundler: failed to load command: jekyll (/home/runner/work/mzagaja.github.io/mzagaja.github.io/vendor/bundle/ruby/3.1.0/bin/jekyll)
[153](https://github.com/mzagaja/mzagaja.github.io/actions/runs/3523413057/jobs/5907545090#step:3:163)
  /home/runner/work/mzagaja.github.io/mzagaja.github.io/vendor/bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `require': libffi.so.7: cannot open shared object file: No such file or directory -
```

The [commit that broke it](https://github.com/mzagaja/mzagaja.github.io/commit/4e9f2a8baa81ecca6dcbf5cefe54a363eac30077) simply added a link, so I think it's an issue with this action.

**Comment by dieghernan** [comment]
HI, nothing has changed in the action in the last month:

https://github.com/dieghernan/algolia-jekyll-action/commits/main/action.yml


I see that you use 

```yaml

ruby-version: '3.1'
```
Maybe it is worth to remove it and recheck.


I re-runed also an instace now (see https://github.com/dieghernan/chulapa/actions/runs/3523589649) and it is working. Could you please try this config on your action?:

```yaml

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch: 

name: algolia-search
jobs:
  algolia-search:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Algolia Jekyll Action
        uses: dieghernan/algolia-jekyll-action@main
        with:
          APIKEY: '${{ secrets.ALGOLIA_API_KEY }}'


```
